### ISSUE TITLE
componentWillUnmount timer is still in progress error

### ISSUE THREAD

**Issue by timothyallan** [reactjs/react-chartjs#135]
I'm using 
`"react-chartjs": "jhudson8/react-chartjs#chartjs-v2"`
`"chart.js": "2.2.0-rc.1"`
`"react": "^15.2.1"`

I've got a dropdown which lets me pick different charts. I can show the chart once just fine, in fact, I can go through all the charts and it works great... as soon as I pick a chart that I've displayed already, I get 

`Warning: There is an internal error in the React performance measurement code. Did not expect componentDidUpdate timer to start while componentWillUnmount timer is still in progress for another instance.`

I'm not doing anything fancy to display the reports, no timers or anything, simply flicking them on and off using something like 

```
 {this.state.reportSelected === MY_SUPER_REPORT ? <ReportComponent /> : null}
```

This is for both Line and Doughnut charts, and all the others too I'd imagine. This worked great forever with the v1 charts, but after converting everything to v2, this has popped up. Any ideas?

**Comment by wwalser** [comment]
There is currently an [open bug in React where this error message can be mistakenly triggered when a component throws an error](https://github.com/facebook/react/issues/6949). Please check the console for any other error messages and if that doesn't work, step through your code carefully in a debugger to see if it's throwing any unexpected errors. 

If that's not the code, the maintainers will likely need to see code the reproduces the problem in order to understand what is causing the problem.

**Comment by timothyallan** [comment]
Yep, that's what it was @wwalser, thanks for the link. Hopefully the React gang can get it fixed up for the next release.
